/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export type addPermissions = boolean;

export type getPermissions = any;

export type login = boolean;

export type logout = boolean;

export type register = boolean;

export type removePermissions = boolean;
