/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface baseInput {
  body: {
      token: string;
    };
  query?: undefined;
  user: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}

export interface baseOutput {
  message?: string;
  result: any;
}

export type jwtToken = string;

export interface login {
  token: string;
}

export interface userSession {
  email: string;
  exp: number;
  iat: number;
  id: string;
  name: string;
}
