/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface checkSession {
  message?: string;
  result: any;
}

export interface login {
  message?: string;
  result: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}

export interface logout {
  message?: string;
  result: any;
}
