/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { UserSession } from '../..';

export interface LoginOutput {
  message?: string;
  result: UserSession;
}
