/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface checkSession {
  body?: undefined;
  query?: undefined;
  user: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}

export interface login {
  body: {
      token: string;
    };
  query?: undefined;
  user?: undefined;
}

export interface logout {
  body?: undefined;
  query?: undefined;
  user: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}
