/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface baseInput {
  body: {
      files: any;
      name: string;
      records: object[];
    } | {
      files?: any;
      id: string;
      name?: string;
      records?: any[];
    } | {
      files: any;
      id: string;
    };
  query?: undefined;
  user: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}

export interface baseOutput {
  message?: string;
  result: any;
}

export interface createTemplateData {
  files: any;
  name: string;
  records: object[];
}

export interface queryImageData {
  id: string;
}

export interface queryTemplatesData {
  page?: number;
  pageSize?: number;
}

export interface removeImageData {
  id: string;
}

export interface removeTemplateData {
  id: string;
}

export interface updateTemplateData {
  files?: any;
  id: string;
  name?: string;
  records?: any[];
}

export interface uploadImageData {
  files: any;
  id: string;
}
