/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { ObjectId } from '..';

export interface CreateTemplateSchema {
  files: any;
  name: string;
  records: object[];
}

export interface QueryImageSchema {
  id: ObjectId;
}

export interface QueryTemplatesSchema {
  page?: number;
  pageSize?: number;
}

export interface UpdateTemplateSchema {
  files?: any;
  id: ObjectId;
  name?: string;
  records?: any[];
}

export interface UploadImageSchema {
  files: any;
  id: ObjectId;
}
