/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface queryTemplateImage {
  body?: undefined;
  params: {
    id: string;
  };
  query?: undefined;
  user?: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}

export interface removeTemplateImage {
  body?: undefined;
  params: {
    id: string;
  };
  query?: undefined;
  user: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}

export interface uploadTemplateImage {
  body: {
    files: any;
    id: string;
  };
  query?: undefined;
  user: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}
