/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createTemplate {
  body: {
    files: any;
    name: string;
    records: object[];
  };
  query?: undefined;
  user: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}

export interface queryTemplates {
  body?: undefined;
  query: {
    page?: number;
    pageSize?: number;
  };
  user?: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}

export interface removeTemplate {
  body?: undefined;
  query: {
    id: string;
  };
  user: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}

export interface updateTemplate {
  body: {
    files?: any;
    id: string;
    name?: string;
    records?: any[];
  };
  query?: undefined;
  user: {
    email: string;
    exp: number;
    iat: number;
    id: string;
    name: string;
  };
}
